platform: x64

environment:
 matrix:
  - DC: ldc
    DVersion: 1.1.0
    arch: x64
  - DC: ldc
    DVersion: 1.2.0
    arch: x64

skip_tags: true
branches:
  only:
    - master

install:
  - ps: function SetUpDCompiler
        {
          echo "downloading ...";
          if($env:arch -eq "x86"){
            $env:DConf = "m32";
          }
          elseif($env:arch -eq "x64"){
            $env:DConf = "m64";
          }
          $env:toolchain = "msvc";
          $version = $env:DVersion;
          Invoke-WebRequest "https://github.com/ldc-developers/ldc/releases/download/v$($version)/ldc2-$($version)-win64-msvc.zip" -OutFile "c:\ldc.zip";
          echo "finished.";
          pushd c:\\;
          7z x ldc.zip > $null;
          popd;
        }
  - ps: SetUpDCompiler
  - powershell -Command Invoke-WebRequest https://code.dlang.org/files/dub-1.0.0-windows-x86.zip -OutFile dub.zip
  - 7z x dub.zip -odub > nul
  - set PATH=%CD%\%binpath%;%CD%\dub;%PATH%
  - dub --version

before_build:
  - ps: if($env:arch -eq "x86"){
            $env:compilersetupargs = "x86";
            $env:Darch = "x86";
          }
        elseif($env:arch -eq "x64"){
            $env:compilersetupargs = "amd64";
            $env:Darch = "x86_64";
        }
  - ps:
        $version = $env:DVersion;
        $env:PATH += ";C:\ldc2-$($version)-win64-msvc\bin";
        $env:DC = "ldmd2";
  - ps: $env:compilersetup = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall";
  - '"%compilersetup%" %compilersetupargs%'



test_script:
 - echo %PLATFORM%
 - echo %Darch%
 - echo %DC%
 - echo %PATH%
 - '%DC% --version'
 - dub test --arch %Darch% dplug:core
 - dub test --arch %Darch% dplug:client
 - dub test --arch %Darch% dplug:host
 - dub test --arch %Darch% dplug:vst
 - dub test --arch %Darch% dplug:dsp
 - dub test --arch %Darch% dplug:gui
 - dub test --arch %Darch% dplug:window
